"""add users table

Revision ID: 1511af3f566d
Revises: d38c53db1542
Create Date: 2025-12-18 15:13:14.113269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1511af3f566d'
down_revision: Union[str, Sequence[str], None] = 'd38c53db1542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE authproviderenum ADD VALUE 'github'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
