"""очистил 

Revision ID: 38498491d443
Revises: 
Create Date: 2026-03-21 21:23:17.953193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38498491d443'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_metrics', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('test_metrics', 'metric_name')
    op.drop_column('test_metrics', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_metrics', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('test_metrics', sa.Column('metric_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('test_metrics', 'name')
    # ### end Alembic commands ###
