"""dev migration

Revision ID: 4d9ba3b5a3cb
Revises: 40d36dde8c05
Create Date: 2026-01-12 17:06:04.303037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9ba3b5a3cb'
down_revision: Union[str, Sequence[str], None] = '40d36dde8c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscriptions', sa.Column('auto_renew', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('user_subscriptions_user_id_key'), 'user_subscriptions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_subscriptions_user_id_key'), 'user_subscriptions', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_subscriptions', 'auto_renew')
    # ### end Alembic commands ###
