"""add test tables

Revision ID: 53f0d9f2438e
Revises: 2ef98e6c00fb
Create Date: 2026-03-21 09:00:28.010420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53f0d9f2438e'
down_revision: Union[str, Sequence[str], None] = '2ef98e6c00fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('psychologist_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('public_link_token', sa.String(), nullable=False),
    sa.Column('access_until', sa.Date(), nullable=True),
    sa.Column('client_can_view_report', sa.Boolean(), nullable=False),
    sa.Column('attempts_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['psychologist_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_link_token')
    )
    op.create_table('report_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.BigInteger(), nullable=False),
    sa.Column('audience', sa.Enum('client', 'career_guidance_specialist', name='reportaudience'), nullable=False),
    sa.Column('template_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'audience', name='uq_report_template_audience')
    )
    op.create_table('test_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.BigInteger(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('formula', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_profile_fields',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('text', 'number', 'date', 'email', 'phone', name='profilefieldtype'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'position', name='uq_test_profile_field_position')
    )
    op.create_table('test_sections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'position', name='uq_test_section_position')
    )
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('test_id', sa.BigInteger(), nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('text', 'textarea', 'single_choice', 'multiple_choice', 'boolean', 'number', 'slider', 'datetime', 'rating_scale', name='questiontype'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['test_sections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_id', 'position', name='uq_question_position')
    )
    op.create_table('test_attempt_profile_values',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('profile_field_id', sa.BigInteger(), nullable=False),
    sa.Column('text_value', sa.String(), nullable=True),
    sa.Column('number_value', sa.Numeric(), nullable=True),
    sa.Column('date_value', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_field_id'], ['test_profile_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'profile_field_id', name='uq_attempt_profile_value')
    )
    op.create_table('question_options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'position', name='uq_question_option_position')
    )
    op.create_table('user_answers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('text_answer', sa.String(), nullable=True),
    sa.Column('boolean_answer', sa.Boolean(), nullable=True),
    sa.Column('number_answer', sa.Numeric(), nullable=True),
    sa.Column('datetime_answer', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['test_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_user_answer')
    )
    op.create_table('user_answer_options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_answer_id', sa.BigInteger(), nullable=False),
    sa.Column('option_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['question_options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_answer_id'], ['user_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_answer_id', 'option_id', name='uq_user_answer_option')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answer_options')
    op.drop_table('user_answers')
    op.drop_table('question_options')
    op.drop_table('test_attempt_profile_values')
    op.drop_table('questions')
    op.drop_table('test_sections')
    op.drop_table('test_profile_fields')
    op.drop_table('test_metrics')
    op.drop_table('test_attempts')
    op.drop_table('report_templates')
    op.drop_table('tests')
    # ### end Alembic commands ###
