"""add is verifed

Revision ID: ea49dc4cfeae
Revises: 5d043c79f9a0
Create Date: 2025-10-15 13:15:47.375044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea49dc4cfeae'
down_revision: Union[str, Sequence[str], None] = '5d043c79f9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем колонку как nullable
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    
    # Устанавливаем значение по умолчанию для существующих пользователей
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")
    
    # Теперь делаем колонку NOT NULL
    op.alter_column('users', 'email_verified', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
